"""level_up_fase_b0_modelado

Revision ID: 242b98b667ff
Revises: v5w6x7y8z9a0
Create Date: 2026-05-18 11:23:23.912813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '242b98b667ff'
down_revision: Union[str, None] = 'v5w6x7y8z9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capacidades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.Enum('tecnica', 'operativa', 'seguridad', 'calidad', name='categoria_capacidad_enum'), nullable=False),
    sa.Column('nivel_max', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('proveedor', sa.String(length=255), nullable=True),
    sa.Column('duracion_horas', sa.Integer(), nullable=False),
    sa.Column('cupo_max', sa.Integer(), nullable=True),
    sa.Column('instructor', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.Enum('tecnico', 'calidad', 'seguridad', 'operativo', 'blanda', name='categoria_curso_enum'), nullable=False),
    sa.Column('modalidad', sa.String(length=50), nullable=False),
    sa.Column('sesiones_anio', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habilidades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('tecnica', 'blanda', 'operativa', 'critica', name='tipo_habilidad_enum'), nullable=False),
    sa.Column('nivel_max', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sugerencias_capacitacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('justificacion', sa.Text(), nullable=True),
    sa.Column('brecha_pct', sa.Float(), nullable=True),
    sa.Column('adopcion_sector_pct', sa.Float(), nullable=True),
    sa.Column('capacidades_afectadas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('areas_afectadas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('personas_alcanzables', sa.Integer(), nullable=True),
    sa.Column('duracion_sugerida', sa.String(length=100), nullable=True),
    sa.Column('inversion_estimada', sa.Float(), nullable=True),
    sa.Column('proveedor_sugerido', sa.String(length=255), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('activa', 'aprobada', 'pospuesta', 'descartada', name='estado_sugerencia_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('prioridad >= 1 AND prioridad <= 5', name='ck_sug_prioridad'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluaciones_capacidad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('capacidad_id', sa.Integer(), nullable=False),
    sa.Column('nivel_actual', sa.Integer(), nullable=False),
    sa.Column('nivel_requerido', sa.Integer(), nullable=False),
    sa.Column('fecha_evaluacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('evaluador_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('nivel_actual >= 1 AND nivel_actual <= 5', name='ck_eval_cap_nivel_actual'),
    sa.CheckConstraint('nivel_requerido >= 1 AND nivel_requerido <= 5', name='ck_eval_cap_nivel_req'),
    sa.ForeignKeyConstraint(['capacidad_id'], ['capacidades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['evaluador_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empleado_id', 'capacidad_id', name='uq_eval_capacidad_vigente')
    )
    op.create_table('evaluaciones_habilidad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('habilidad_id', sa.Integer(), nullable=False),
    sa.Column('nivel_actual', sa.Integer(), nullable=False),
    sa.Column('fecha_evaluacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('evaluador_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('nivel_actual >= 1 AND nivel_actual <= 4', name='ck_eval_hab_nivel_actual'),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['evaluador_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['habilidad_id'], ['habilidades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empleado_id', 'habilidad_id', name='uq_eval_habilidad_vigente')
    )
    op.create_table('opls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('proceso', sa.String(length=255), nullable=True),
    sa.Column('maquina', sa.String(length=255), nullable=True),
    sa.Column('aprobador_id', sa.Integer(), nullable=True),
    sa.Column('estado_aprobacion', sa.Enum('borrador', 'revision', 'aprobada', name='estado_aprobacion_opl_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aprobador_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('planes_desarrollo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_fin_estimada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'completado', 'cancelado', name='estado_plan_desarrollo_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capacidad_puesto_perfil',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('capacidad_id', sa.Integer(), nullable=False),
    sa.Column('puesto_perfil_id', sa.Integer(), nullable=False),
    sa.Column('nivel_requerido', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('nivel_requerido >= 1 AND nivel_requerido <= 5', name='ck_cap_puesto_nivel_rango'),
    sa.ForeignKeyConstraint(['capacidad_id'], ['capacidades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['puesto_perfil_id'], ['puestos_perfil.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capacidad_id', 'puesto_perfil_id', name='uq_capacidad_puesto')
    )
    op.create_table('encuestas_post_curso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('capacitacion_id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('score_general', sa.Integer(), nullable=False),
    sa.Column('score_instructor', sa.Integer(), nullable=False),
    sa.Column('score_contenido', sa.Integer(), nullable=False),
    sa.Column('score_aplicabilidad', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score_aplicabilidad >= 1 AND score_aplicabilidad <= 5', name='ck_enc_score_aplic'),
    sa.CheckConstraint('score_contenido >= 1 AND score_contenido <= 5', name='ck_enc_score_cont'),
    sa.CheckConstraint('score_general >= 1 AND score_general <= 5', name='ck_enc_score_gen'),
    sa.CheckConstraint('score_instructor >= 1 AND score_instructor <= 5', name='ck_enc_score_inst'),
    sa.ForeignKeyConstraint(['capacitacion_id'], ['capacitaciones.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capacitacion_id', 'empleado_id', name='uq_encuesta_cap_emp')
    )
    op.create_table('evidencias_capacitacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.Enum('foto', 'documento', 'video', 'firma', name='tipo_evidencia_cap_enum'), nullable=False),
    sa.Column('archivo_url', sa.String(length=500), nullable=False),
    sa.Column('capacitacion_id', sa.Integer(), nullable=True),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'validada', 'devuelta', name='estado_evidencia_cap_enum'), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['capacitacion_id'], ['capacitaciones.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opl_versiones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opl_id', sa.Integer(), nullable=False),
    sa.Column('version_num', sa.Integer(), nullable=False),
    sa.Column('archivo_url', sa.String(length=500), nullable=False),
    sa.Column('cambios_descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['opl_id'], ['opls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_etapas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('curso', 'opl', 'evaluacion', 'proyecto', name='tipo_plan_etapa_enum'), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'en_curso', 'completada', name='estado_plan_etapa_enum'), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_completado', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['planes_desarrollo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidencia_firmas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evidencia_id', sa.Integer(), nullable=False),
    sa.Column('firmante_id', sa.Integer(), nullable=False),
    sa.Column('rol_firma', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'firmada', 'rechazada', name='estado_firma_enum'), nullable=False),
    sa.Column('fecha_firma', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evidencia_id'], ['evidencias_capacitacion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firmante_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidencia_id', 'firmante_id', 'rol_firma', name='uq_firma_evidencia_rol')
    )
    op.add_column('capacitaciones', sa.Column('curso_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_capacitaciones_curso_id', 'capacitaciones', 'cursos', ['curso_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_capacitaciones_curso_id', 'capacitaciones', type_='foreignkey')
    op.drop_column('capacitaciones', 'curso_id')
    op.drop_table('evidencia_firmas')
    op.drop_table('plan_etapas')
    op.drop_table('opl_versiones')
    op.drop_table('evidencias_capacitacion')
    op.drop_table('encuestas_post_curso')
    op.drop_table('capacidad_puesto_perfil')
    op.drop_table('planes_desarrollo')
    op.drop_table('opls')
    op.drop_table('evaluaciones_habilidad')
    op.drop_table('evaluaciones_capacidad')
    op.drop_table('sugerencias_capacitacion')
    op.drop_table('habilidades')
    op.drop_table('cursos')
    op.drop_table('capacidades')
    sa.Enum(name='categoria_capacidad_enum').drop(op.get_bind())
    sa.Enum(name='tipo_habilidad_enum').drop(op.get_bind())
    sa.Enum(name='categoria_curso_enum').drop(op.get_bind())
    sa.Enum(name='estado_aprobacion_opl_enum').drop(op.get_bind())
    sa.Enum(name='tipo_evidencia_cap_enum').drop(op.get_bind())
    sa.Enum(name='estado_evidencia_cap_enum').drop(op.get_bind())
    sa.Enum(name='estado_firma_enum').drop(op.get_bind())
    sa.Enum(name='estado_sugerencia_enum').drop(op.get_bind())
    sa.Enum(name='estado_plan_desarrollo_enum').drop(op.get_bind())
    sa.Enum(name='tipo_plan_etapa_enum').drop(op.get_bind())
    sa.Enum(name='estado_plan_etapa_enum').drop(op.get_bind())
    # ### end Alembic commands ###
