"""initial_schema

Revision ID: c06e332f3cce
Revises: 
Create Date: 2026-03-31 00:04:38.417130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c06e332f3cce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comedores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('turno_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('it_sync_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operacion', sa.Enum('insert', 'update', 'deactivate', name='it_sync_operacion_enum'), nullable=False),
    sa.Column('empleado_id', sa.String(length=50), nullable=False),
    sa.Column('datos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sincronizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('ok', 'error', name='it_sync_status_enum'), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('permisos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('nombre', name='uq_roles_nombre')
    )
    op.create_table('token_blacklist',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_table('tress_robot_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estado', sa.Enum('pending', 'done', 'error', 'retrying', name='tress_queue_estado_enum'), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empleados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('num_empleado', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('apellido', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('departamento', sa.String(length=150), nullable=True),
    sa.Column('puesto', sa.String(length=150), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('num_empleado')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('modulo', sa.String(length=100), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('datos_antes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('datos_despues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comedor_registros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('comedor_id', sa.Integer(), nullable=False),
    sa.Column('semana', sa.Date(), nullable=False),
    sa.Column('tipo_platillo', sa.Enum('normal', 'dieta', name='comedor_tipo_platillo_enum'), nullable=False),
    sa.Column('acceso_concedido', sa.Boolean(), nullable=False),
    sa.Column('rfid_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comedor_id'], ['comedores.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidencias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entidad_tipo', sa.Enum('incidencia', 'acta', name='evidencia_entidad_tipo_enum'), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('archivo_path', sa.String(length=500), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('tamano_bytes', sa.Integer(), nullable=False),
    sa.Column('subido_por', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['subido_por'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidencias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('open', 'in_review', 'resolved', 'closed', name='incidencia_estado_enum'), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_semanal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comedor_id', sa.Integer(), nullable=False),
    sa.Column('semana', sa.Date(), nullable=False),
    sa.Column('dia', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.Enum('normal', 'dieta', name='menu_tipo_enum'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('foto_path', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comedor_id'], ['comedores.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('email', 'in_app', name='notificacion_tipo_enum'), nullable=False),
    sa.Column('asunto', sa.String(length=255), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('enviada', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destinatario_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitudes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('vacaciones', 'home_office', name='solicitud_tipo_enum'), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('pending', 'approved', 'rejected', 'cancelled', 'overridden', name='solicitud_estado_enum'), nullable=False),
    sa.Column('nivel_actual', sa.Integer(), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actas_administrativas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incidencia_id', sa.Integer(), nullable=True),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('contenido_ia', sa.Text(), nullable=True),
    sa.Column('contenido_final', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('draft', 'pending_sign', 'signed', 'archived', name='acta_estado_enum'), nullable=False),
    sa.Column('generado_por', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['generado_por'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['incidencia_id'], ['incidencias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitud_aprobaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('aprobador_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.Enum('approve', 'reject', 'override', name='aprobacion_accion_enum'), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aprobador_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acta_aprobaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('acta_id', sa.Integer(), nullable=False),
    sa.Column('firmante_id', sa.Integer(), nullable=False),
    sa.Column('rol_firmante', sa.String(length=100), nullable=False),
    sa.Column('firma_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['acta_id'], ['actas_administrativas.id'], ),
    sa.ForeignKeyConstraint(['firmante_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acta_aprobaciones')
    op.drop_table('solicitud_aprobaciones')
    op.drop_table('actas_administrativas')
    op.drop_table('solicitudes')
    op.drop_table('notificaciones')
    op.drop_table('menu_semanal')
    op.drop_table('incidencias')
    op.drop_table('evidencias')
    op.drop_table('comedor_registros')
    op.drop_table('audit_log')
    op.drop_table('empleados')
    op.drop_table('tress_robot_queue')
    op.drop_table('token_blacklist')
    op.drop_table('roles')
    op.drop_table('it_sync_log')
    op.drop_table('comedores')
    # ### end Alembic commands ###
