import type { ConciliacionPageViewModel } from "./types.ts";

/** Datos simulados alineados al mockup de Conciliación de Nómina. */
export function buildConciliacionViewModel(): ConciliacionPageViewModel {
  return {
    periodoEstado: "con_diferencias",
    periodoEstadoLabel: "Con diferencias",
    filtros: {
      razonSocial: "LEONI Wiring Systems · Hermosillo",
      periodo: "Mayo 2026 - Acumulado",
      centro: "Todas las plantas",
      ultimaCorrida: "Última corrida 01/06/26 · 06:12",
    },
    summaryCards: [
      {
        id: "percepciones",
        label: "Total Percepciones Nómina",
        value: "$125.3M",
        footer: "Sueldos, bonos, vales y fondos",
      },
      {
        id: "deducciones",
        label: "Total Deducciones Nómina",
        value: "$36.0M",
        footer: "Impuestos, créditos y otras",
      },
      {
        id: "contabilidad",
        label: "Total Contabilidad",
        value: "$156.6M",
        footer: "Directos + Indirectos cuadrados",
        accent: "info",
      },
      {
        id: "diferencia",
        label: "Diferencia Total",
        value: "$519K",
        footer: "Nómina vs Contabilidad",
        accent: "danger",
        badgeLabel: "10 concept.",
        badgeTone: "danger",
      },
      {
        id: "conciliados",
        label: "Registros Conciliados",
        value: "8",
        footer: "16 sin contabilidad",
        accent: "success",
      },
      {
        id: "diferencias",
        label: "Registros con Diferencias",
        value: "10",
        footer: "4 críticas · 6 menores",
        accent: "warning",
      },
    ],
    categorias: [
      {
        id: "percepciones",
        nombre: "Percepciones",
        tipoLabel: "Percepción",
        expanded: true,
        difCount: 3,
        nominaAcum: 98_420_150.42,
        tressAcum: 98_416_937.55,
        difNomTress: 3_212.87,
        directosContab: 72_104_880.0,
        indirectosContab: 26_315_270.42,
        totalContab: 98_420_150.42,
        difNomContab: 0,
        filas: [
          {
            id: "sueldo-base",
            nombre: "Sueldo base",
            estatus: "conciliado",
            nominaAcum: 68_240_500.0,
            tressAcum: 68_240_500.0,
            difNomTress: 0,
            directosContab: 51_180_375.0,
            indirectosContab: 17_060_125.0,
            totalContab: 68_240_500.0,
            difNomContab: 0,
          },
          {
            id: "bono-productividad",
            nombre: "Bono productividad",
            estatus: "menor",
            nominaAcum: 12_450_800.0,
            tressAcum: 12_450_200.0,
            difNomTress: 600.0,
            directosContab: 9_338_100.0,
            indirectosContab: 3_112_700.0,
            totalContab: 12_450_800.0,
            difNomContab: 0,
          },
          {
            id: "vales-despensa",
            nombre: "Vales de despensa",
            estatus: "sin_contab",
            nominaAcum: 8_920_450.42,
            tressAcum: 8_920_450.42,
            difNomTress: 0,
            directosContab: null,
            indirectosContab: null,
            totalContab: null,
            difNomContab: null,
          },
          {
            id: "fondo-ahorro",
            nombre: "Fondo de ahorro",
            estatus: "critica",
            nominaAcum: 5_312_400.0,
            tressAcum: 5_309_187.13,
            difNomTress: 3_212.87,
            directosContab: 3_984_300.0,
            indirectosContab: 1_328_100.0,
            totalContab: 5_312_400.0,
            difNomContab: 0,
          },
          {
            id: "prima-vacacional",
            nombre: "Prima vacacional",
            estatus: "conciliado",
            nominaAcum: 3_496_000.0,
            tressAcum: 3_496_000.0,
            difNomTress: 0,
            directosContab: 2_622_000.0,
            indirectosContab: 874_000.0,
            totalContab: 3_496_000.0,
            difNomContab: 0,
          },
        ],
      },
      {
        id: "deducciones",
        nombre: "Deducciones",
        tipoLabel: "Deducción",
        expanded: true,
        difCount: 4,
        nominaAcum: 36_012_480.18,
        tressAcum: 36_009_100.0,
        difNomTress: 3_380.18,
        directosContab: 27_009_360.0,
        indirectosContab: 9_003_120.18,
        totalContab: 36_012_480.18,
        difNomContab: 0,
        filas: [
          {
            id: "isr",
            nombre: "ISR retenido",
            estatus: "conciliado",
            nominaAcum: 14_820_300.0,
            tressAcum: 14_820_300.0,
            difNomTress: 0,
            directosContab: 11_115_225.0,
            indirectosContab: 3_705_075.0,
            totalContab: 14_820_300.0,
            difNomContab: 0,
          },
          {
            id: "imss",
            nombre: "IMSS trabajador",
            estatus: "menor",
            nominaAcum: 6_540_120.0,
            tressAcum: 6_539_800.0,
            difNomTress: 320.0,
            directosContab: 4_905_090.0,
            indirectosContab: 1_635_030.0,
            totalContab: 6_540_120.0,
            difNomContab: 0,
          },
          {
            id: "credito-fonacot",
            nombre: "Crédito FONACOT",
            estatus: "critica",
            nominaAcum: 2_180_460.18,
            tressAcum: 2_177_400.0,
            difNomTress: 3_060.18,
            directosContab: 1_635_345.0,
            indirectosContab: 545_115.18,
            totalContab: 2_180_460.18,
            difNomContab: 0,
          },
          {
            id: "pension-alimenticia",
            nombre: "Pensión alimenticia",
            estatus: "sin_contab",
            nominaAcum: 1_420_600.0,
            tressAcum: 1_420_600.0,
            difNomTress: 0,
            directosContab: null,
            indirectosContab: null,
            totalContab: null,
            difNomContab: null,
          },
          {
            id: "infonavit",
            nombre: "Descuento INFONAVIT",
            estatus: "menor",
            nominaAcum: 11_051_000.0,
            tressAcum: 11_051_000.0,
            difNomTress: 0,
            directosContab: 8_288_250.0,
            indirectosContab: 2_762_750.0,
            totalContab: 11_051_000.0,
            difNomContab: 0,
          },
        ],
      },
      {
        id: "aportaciones",
        nombre: "Aportaciones patronales",
        tipoLabel: "Aportación",
        expanded: false,
        difCount: 3,
        nominaAcum: 22_168_320.0,
        tressAcum: 22_165_940.0,
        difNomTress: 2_380.0,
        directosContab: 16_626_240.0,
        indirectosContab: 5_542_080.0,
        totalContab: 22_168_320.0,
        difNomContab: 0,
        filas: [
          {
            id: "imss-patronal",
            nombre: "IMSS patronal",
            estatus: "conciliado",
            nominaAcum: 9_840_200.0,
            tressAcum: 9_840_200.0,
            difNomTress: 0,
            directosContab: 7_380_150.0,
            indirectosContab: 2_460_050.0,
            totalContab: 9_840_200.0,
            difNomContab: 0,
          },
          {
            id: "rcv",
            nombre: "RCV patronal",
            estatus: "menor",
            nominaAcum: 6_120_480.0,
            tressAcum: 6_119_100.0,
            difNomTress: 1_380.0,
            directosContab: 4_590_360.0,
            indirectosContab: 1_530_120.0,
            totalContab: 6_120_480.0,
            difNomContab: 0,
          },
          {
            id: "infonavit-patronal",
            nombre: "INFONAVIT patronal",
            estatus: "critica",
            nominaAcum: 6_207_640.0,
            tressAcum: 6_206_640.0,
            difNomTress: 1_000.0,
            directosContab: 4_655_730.0,
            indirectosContab: 1_551_910.0,
            totalContab: 6_207_640.0,
            difNomContab: 0,
          },
        ],
      },
    ],
  };
}
