import type { RhSolicitudTablaFila } from "./types.ts";

/**
 * Dataset mock para desarrollo. Sustituir por respuesta de API (`adapter`).
 */
export const RH_SOLICITUDES_MOCK_FILAS: RhSolicitudTablaFila[] = [
  {
    id: 2938,
    empleado_nombre_raw: "MARTÍNEZ LÓPEZ, ANA",
    foto_url: null,
    numero_folio: "SOL-2938",
    area: "Marketing",
    tipo: "vacaciones",
    fecha_solicitud: "2023-10-12",
    fecha_inicio: "2023-10-24",
    fecha_fin: "2023-10-30",
    periodo_etiqueta: null,
    estado: "pending",
    supervisor_id: "sup-1",
    supervisor_nombre: "GARCÍA, CARLOS",
    fecha_aprobacion: null,
  },
  {
    id: 2939,
    empleado_nombre_raw: "RUIZ PÉREZ, LUIS",
    foto_url: null,
    numero_folio: "SOL-2939",
    area: "Desarrollo",
    tipo: "home_office",
    fecha_solicitud: "2023-10-11",
    fecha_inicio: "2023-10-13",
    fecha_fin: "2023-12-31",
    periodo_etiqueta: "Cada viernes",
    estado: "pending",
    supervisor_id: "sup-2",
    supervisor_nombre: "HERRERA, MARÍA",
    fecha_aprobacion: null,
  },
  {
    id: 2940,
    empleado_nombre_raw: "SOTO, DIEGO",
    foto_url: null,
    numero_folio: "SOL-2940",
    area: "Desarrollo",
    tipo: "vacaciones",
    fecha_solicitud: "2023-10-10",
    fecha_inicio: "2023-11-01",
    fecha_fin: "2023-11-05",
    periodo_etiqueta: null,
    estado: "approved",
    supervisor_id: "sup-2",
    supervisor_nombre: "HERRERA, MARÍA",
    fecha_aprobacion: "2023-10-10",
  },
  {
    id: 2941,
    empleado_nombre_raw: "FLORES, ELENA",
    foto_url: null,
    numero_folio: "SOL-2941",
    area: "RH",
    tipo: "home_office",
    fecha_solicitud: "2023-10-09",
    fecha_inicio: "2023-10-09",
    fecha_fin: "2023-10-09",
    periodo_etiqueta: null,
    estado: "rejected",
    supervisor_id: "sup-1",
    supervisor_nombre: "GARCÍA, CARLOS",
    fecha_aprobacion: null,
  },
  {
    id: 2942,
    empleado_nombre_raw: "NÚÑEZ, PATRICIA",
    foto_url: null,
    numero_folio: "SOL-2942",
    area: "Marketing",
    tipo: "vacaciones",
    fecha_solicitud: "2023-10-08",
    fecha_inicio: "2023-12-20",
    fecha_fin: "2024-01-03",
    periodo_etiqueta: null,
    estado: "pending",
    supervisor_id: "sup-1",
    supervisor_nombre: "GARCÍA, CARLOS",
    fecha_aprobacion: null,
  },
  {
    id: 2943,
    empleado_nombre_raw: "ORTIZ, JORGE",
    foto_url: null,
    numero_folio: "SOL-2943",
    area: "Producción",
    tipo: "home_office",
    fecha_solicitud: "2023-10-07",
    fecha_inicio: "2023-10-16",
    fecha_fin: "2023-10-20",
    periodo_etiqueta: null,
    estado: "cancelled",
    supervisor_id: "sup-3",
    supervisor_nombre: "LUNA, ROBERTO",
    fecha_aprobacion: null,
  },
  {
    id: 2944,
    empleado_nombre_raw: "CASTRO, MÓNICA",
    foto_url: null,
    numero_folio: "SOL-2944",
    area: "Desarrollo",
    tipo: "vacaciones",
    fecha_solicitud: "2023-10-06",
    fecha_inicio: "2023-10-02",
    fecha_fin: "2023-10-06",
    periodo_etiqueta: null,
    estado: "approved",
    supervisor_id: "sup-2",
    supervisor_nombre: "HERRERA, MARÍA",
    fecha_aprobacion: "2023-10-06",
  },
  {
    id: 2945,
    empleado_nombre_raw: "VARGAS, SERGIO",
    foto_url: null,
    numero_folio: "SOL-2945",
    area: "Producción",
    tipo: "vacaciones",
    fecha_solicitud: "2023-10-05",
    fecha_inicio: "2023-10-15",
    fecha_fin: "2023-10-22",
    periodo_etiqueta: null,
    estado: "pending",
    supervisor_id: "sup-3",
    supervisor_nombre: "LUNA, ROBERTO",
    fecha_aprobacion: null,
  },
  {
    id: 2946,
    empleado_nombre_raw: "RAMOS, CLAUDIA",
    foto_url: null,
    numero_folio: "SOL-2946",
    area: "Marketing",
    tipo: "home_office",
    fecha_solicitud: "2023-10-04",
    fecha_inicio: "2023-10-11",
    fecha_fin: "2023-10-11",
    periodo_etiqueta: null,
    estado: "approved",
    supervisor_id: "sup-1",
    supervisor_nombre: "GARCÍA, CARLOS",
    fecha_aprobacion: "2023-10-04",
  },
  {
    id: 2947,
    empleado_nombre_raw: "MENDOZA, FERNANDO",
    foto_url: null,
    numero_folio: "SOL-2947",
    area: "Desarrollo",
    tipo: "home_office",
    fecha_solicitud: "2023-10-03",
    fecha_inicio: "2023-10-18",
    fecha_fin: "2023-10-18",
    periodo_etiqueta: null,
    estado: "pending",
    supervisor_id: "sup-2",
    supervisor_nombre: "HERRERA, MARÍA",
    fecha_aprobacion: null,
  },
  {
    id: 2948,
    empleado_nombre_raw: "IBARRA, LETICIA",
    foto_url: null,
    numero_folio: "SOL-2948",
    area: "RH",
    tipo: "vacaciones",
    fecha_solicitud: "2023-10-02",
    fecha_inicio: "2023-11-10",
    fecha_fin: "2023-11-17",
    periodo_etiqueta: null,
    estado: "overridden",
    supervisor_id: "sup-1",
    supervisor_nombre: "GARCÍA, CARLOS",
    fecha_aprobacion: "2023-10-02",
  },
  {
    id: 2949,
    empleado_nombre_raw: "PEÑA, RICARDO",
    foto_url: null,
    numero_folio: "SOL-2949",
    area: "Producción",
    tipo: "vacaciones",
    fecha_solicitud: "2023-10-01",
    fecha_inicio: "2023-09-25",
    fecha_fin: "2023-09-29",
    periodo_etiqueta: null,
    estado: "approved",
    supervisor_id: "sup-3",
    supervisor_nombre: "LUNA, ROBERTO",
    fecha_aprobacion: "2023-10-01",
  },
  {
    id: 2950,
    empleado_nombre_raw: "DELGADO, ANDREA",
    foto_url: null,
    numero_folio: "SOL-2950",
    area: "Marketing",
    tipo: "home_office",
    fecha_solicitud: "2023-09-30",
    fecha_inicio: "2023-10-05",
    fecha_fin: "2023-10-05",
    periodo_etiqueta: null,
    estado: "pending",
    supervisor_id: "sup-1",
    supervisor_nombre: "GARCÍA, CARLOS",
    fecha_aprobacion: null,
  },
  {
    id: 2951,
    empleado_nombre_raw: "CAMPOS, HÉCTOR",
    foto_url: null,
    numero_folio: "SOL-2951",
    area: "Desarrollo",
    tipo: "vacaciones",
    fecha_solicitud: "2023-09-29",
    fecha_inicio: "2023-12-01",
    fecha_fin: "2023-12-08",
    periodo_etiqueta: null,
    estado: "rejected",
    supervisor_id: "sup-2",
    supervisor_nombre: "HERRERA, MARÍA",
    fecha_aprobacion: null,
  },
  {
    id: 2952,
    empleado_nombre_raw: "REYES, GABRIELA",
    foto_url: null,
    numero_folio: "SOL-2952",
    area: "Producción",
    tipo: "home_office",
    fecha_solicitud: "2023-09-28",
    fecha_inicio: "2023-10-02",
    fecha_fin: "2023-10-06",
    periodo_etiqueta: null,
    estado: "pending",
    supervisor_id: "sup-3",
    supervisor_nombre: "LUNA, ROBERTO",
    fecha_aprobacion: null,
  },
];
