# CRITICAL: All models must be imported here so Alembic autogenerate detects them.
from app.models.roles import Rol
from app.models.catalogos import (
    Area,
    Categoria,
    ClasificacionEmpleado,
    EstadoEmpleado,
    Puesto,
    Subarea,
)
from app.models.empleados import Empleado
from app.models.empleados_rh import (
    EmpleadoCore,
    EmpleadoRhConfig,
    EmpleadoRhHorasExtra,
    EmpleadoRhPermisos,
)
from app.models.turnos import Turno
from app.models.turnos_empleados import TurnoEmpleado
from app.models.vacaciones_disponibles import VacacionesDisponibles
from app.models.homeoffice_tomados import HomeOfficeTomados
from app.models.incidencias_tress import IncidenciaTress
from app.models.solicitudes import Solicitud, SolicitudAprobacion
from app.models.incidencias import Incidencia, Evidencia
from app.models.actas import ActaAdministrativa, ActaAprobacion
from app.models.faltas_retardos import FaltaRetardoEvento, FaltaRetardoRegistroAuditoria
from app.models.viajes_laborales import ViajeLaboral
from app.models.comedor import (
    Comedor,
    ComedorAcceso,
    ComedorCodigoExterno,
    ComedorExternoCorrelativo,
    ComedorRegistro,
    MenuSemanal,
)
from app.models.notificaciones import Notificacion
from app.models.emails import Email
from app.models.auditoria import AuditLog, ItSyncLog, TokenBlacklist
from app.models.bono_historico_import_log import BonoHistoricoImportLog
from app.models.tress import TressRobotQueue
from app.models.clasificacion_puesto import (
    CareerPath,
    CategoriaTarea,
    DisciplinaPuesto,
    FuncionPuesto,
    GlobalGrade,
    CareerLevelGradeMapping,
    PuestoPerfilClasificacionHistorial,
)
from app.models.talento import (
    AccionRecomendada,
    PuestoPerfil, Competencia, CompetenciaRequisito, EvaluacionCompetencia,
    Capacitacion, Inscripcion,
    TareaCatalogo, PerfilTarea, PerfilCualificacion,
    PerfilFunciones, PerfilFuncionesCualificacion, PerfilFuncionesCompetencia,
    PerfilFuncionesTarea, GradoPuesto, PuestoPerfilGrado,
    TipoCompetencia, GrupoCompetencia,
    TipoCualificacionCatalogo, MetodoCalificacion, OpcionCalificacion, CualificacionCatalogo,
    MetodoCalificacionCompetencia,
    PlanDesarrolloIndividual,
)
from app.models.horas_extra import (
    CentroCosto,
    HorasExtraAprobacion,
    HorasExtraAprobador,
    HorasExtraMotivo,
    HorasExtraSolicitud,
    HorasExtraSolicitudDetalle,
)
from app.models.cursos_catalogo import (
    CursoCategoria,
    CursoClasificacion,
    CursoInstructorExterno,
    CursoInstructorInterno,
    CursoProveedor,
    CursoTipo,
)
from app.models.level_up import (
    Capacidad,
    CapacidadPuestoPerfil,
    Habilidad,
    EvaluacionCapacidad,
    EvaluacionHabilidad,
    Curso,
    CursoSesion,
    CursoEmpleado,
    CursoPuesto,
    OPL,
    OPLVersion,
    EvidenciaCapacitacion,
    EvidenciaFirma,
    CursoEncuesta,
    EncuestaPostCurso,
    SugerenciaCapacitacion,
    PlanDesarrollo,
    PlanEtapa,
)
from app.models.juntas import (
    Junta,
    JuntaAsistente,
)
from app.models.proveedores_externos import (
    Proveedor,
    ProveedorPersona,
    CursoExterno,
    ProveedorPersonaCurso,
)
from app.models.evaluacion360 import (
    Eval360Config,
    Eval360Escala,
    Eval360Pregunta,
    Eval360Campana,
    Eval360CampanaCompetencia,
    Eval360CampanaEvaluadorTipo,
    Eval360Participante,
    Eval360Evaluacion,
    Eval360Respuesta,
    Eval360Comentario,
    Eval360Resultado,
    Eval360Plantilla,
    Eval360PlantillaCompetencia,
    Eval360PlantillaEvaluadorTipo,
)
from app.models.encuestas_rh import (
    Encuesta,
    EncuestaPregunta,
    EncuestaOpcion,
    EncuestaParticipante,
    EncuestaRespuestaGrupo,
    EncuestaRespuesta,
    EncuestaRespuestaOpcion,
    EncuestaPlantilla,
)
from app.models.metas import (
    MetaCiclo,
    Meta,
    MetaResultadoClave,
    MetaCheckin,
)
from app.models.ciclo_desempeno import (
    CicloDesempeno,
    CicloDesempenoResultado,
)
from app.models.vistas_rol import VistaRol

__all__ = [
    "Rol",
    "Area",
    "Subarea",
    "Categoria",
    "Puesto",
    "EstadoEmpleado",
    "ClasificacionEmpleado",
    "Empleado",
    "EmpleadoCore",
    "EmpleadoRhConfig",
    "EmpleadoRhPermisos",
    "EmpleadoRhHorasExtra",
    "Turno",
    "TurnoEmpleado",
    "Solicitud",
    "SolicitudAprobacion",
    "Incidencia",
    "Evidencia",
    "ActaAdministrativa",
    "ActaAprobacion",
    "FaltaRetardoEvento",
    "FaltaRetardoRegistroAuditoria",
    "ViajeLaboral",
    "Comedor",
    "ComedorAcceso",
    "ComedorCodigoExterno",
    "ComedorExternoCorrelativo",
    "MenuSemanal",
    "ComedorRegistro",
    "Notificacion",
    "Email",
    "AuditLog",
    "ItSyncLog",
    "TokenBlacklist",
    "BonoHistoricoImportLog",
    "TressRobotQueue",
    "AccionRecomendada",
    "CareerPath",
    "FuncionPuesto",
    "DisciplinaPuesto",
    "CategoriaTarea",
    "GlobalGrade",
    "CareerLevelGradeMapping",
    "PuestoPerfilClasificacionHistorial",
    "GradoPuesto",
    "PuestoPerfilGrado",
    "GrupoCompetencia",
    "TipoCompetencia",
    "TareaCatalogo",
    "MetodoCalificacionCompetencia",
    "PuestoPerfil",
    "Competencia",
    "CompetenciaRequisito",
    "EvaluacionCompetencia",
    "Capacitacion",
    "Inscripcion",
    "PerfilTarea",
    "PerfilCualificacion",
    "PerfilFunciones",
    "PerfilFuncionesCualificacion",
    "PerfilFuncionesCompetencia",
    "PerfilFuncionesTarea",
    "TipoCualificacionCatalogo",
    "MetodoCalificacion",
    "OpcionCalificacion",
    "CualificacionCatalogo",
    "CentroCosto",
    "HorasExtraMotivo",
    "HorasExtraSolicitud",
    "HorasExtraSolicitudDetalle",
    "HorasExtraAprobacion",
    "HorasExtraAprobador",
    "CursoCategoria",
    "CursoTipo",
    "CursoClasificacion",
    "CursoInstructorExterno",
    "CursoInstructorInterno",
    "CursoProveedor",
    "Capacidad",
    "CapacidadPuestoPerfil",
    "Habilidad",
    "EvaluacionCapacidad",
    "EvaluacionHabilidad",
    "Curso",
    "CursoSesion",
    "CursoEmpleado",
    "CursoPuesto",
    "OPL",
    "OPLVersion",
    "EvidenciaCapacitacion",
    "EvidenciaFirma",
    "CursoEncuesta",
    "EncuestaPostCurso",
    "SugerenciaCapacitacion",
    "PlanDesarrollo",
    "PlanEtapa",
    "PlanDesarrolloIndividual",
    "Junta",
    "JuntaAsistente",
    "Eval360Config",
    "Eval360Escala",
    "Eval360Pregunta",
    "Eval360Campana",
    "Eval360CampanaCompetencia",
    "Eval360CampanaEvaluadorTipo",
    "Eval360Participante",
    "Eval360Evaluacion",
    "Eval360Respuesta",
    "Eval360Comentario",
    "Eval360Resultado",
    "Eval360Plantilla",
    "Eval360PlantillaCompetencia",
    "Eval360PlantillaEvaluadorTipo",
    "Encuesta",
    "EncuestaPregunta",
    "EncuestaOpcion",
    "EncuestaParticipante",
    "EncuestaRespuestaGrupo",
    "EncuestaRespuesta",
    "EncuestaRespuestaOpcion",
    "EncuestaPlantilla",
    "MetaCiclo",
    "Meta",
    "MetaResultadoClave",
    "MetaCheckin",
    "CicloDesempeno",
    "CicloDesempenoResultado",
    "VistaRol",
    "VacacionesDisponibles",
    "HomeOfficeTomados",
    "IncidenciaTress",
]
