/**
 * Textos de UI — vista administrativa de incidencias laborales (rol RH).
 */

export const INC_COPY = {
  tituloPagina: "Incidencias",
  listadoTitulo: "Listado de incidencias",
  listadoSubtitulo: (total: number) =>
    total === 1 ? "1 incidencia encontrada" : `${total} incidencias encontradas`,
  listadoDetalleToggle: "Mostrar u ocultar listado completo",
  exportar: "Exportar listado de incidencias",
  nueva: "Nueva incidencia",
  filtrosAvanzadosAria: "Filtros avanzados",
  filtrosToggleMobile: "Filtros de búsqueda",

  analiticaSeccionAria: "Resumen ejecutivo e indicadores",
  analiticaBloquePrincipalAria: "Análisis visual principal",
  analiticaRankingsAria: "Rankings comparativos",
  analiticaAreas: "Áreas con más incidencias",
  analiticaAreasSub: "Top 5 respecto al total filtrado",
  analiticaSubareas: "Subáreas con más incidencias",
  analiticaSubareasSub: "Top 5 respecto al total filtrado",
  analiticaEmpleados: "Empleados con más incidencias",
  analiticaEmpleadosSub: "Top 5 respecto al total filtrado",
  analiticaEmpleadosSegCalTitulo: "Personal con más quejas de seguridad y calidad",
  analiticaEmpleadosSegCalSub: "Top 5 de quejas históricas según filtros aplicados",
  analiticaEmpleadosSegCalVacio: "Sin quejas de seguridad o calidad con los filtros actuales.",
  analiticaRetardosTitulo: "Top 5 empleados con más retardos",
  analiticaRetardosSub: "Incidencias de tipo retardo según filtros aplicados",
  analiticaRetardosVacio: "Sin retardos registrados con los filtros actuales.",
  analiticaTipoTitulo: "Distribución por tipo",
  analiticaTipoSub: "Proporción según clasificación registrada",
  analiticaTendenciaTitulo: "Tendencia por tipo de incidencia",
  analiticaTendenciaSub: "Evolución por tipo según filtros aplicados",
  verRankingCompleto: "Ver ranking completo",
  kpiTotal: "Total de incidencias",
  /** Título KPI en dos líneas (tarjetas analítica). */
  kpiTotalLine1: "Total",
  kpiTotalLine2: "de incidencias",
  kpiSeguridadLine1: "Incidencias",
  kpiSeguridadLine2: "de seguridad",
  kpiCalidadLine1: "Incidencias",
  kpiCalidadLine2: "de calidad",
  kpiAreaTopLine1: "Área",
  kpiAreaTopLine2: "crítica",
  kpiTotalContexto: (abiertas: number, enInv: number) =>
    `${abiertas} abiertas · ${enInv} en investigación`,
  kpiSeguridad: "Incidencias de seguridad",
  kpiSeguridadHint: "Casos ligados a seguridad (tipo o categoría).",
  kpiCalidad: "Incidencias de calidad",
  kpiCalidadHint: "Casos ligados a calidad (tipo o categoría).",
  kpiAreaTop: "Área crítica",
  kpiAreaTopHint: (n: number) => `${n} en el área líder`,
  kpiEmpleadoTop: "Empleado con más incidencias",
  kpiEmpleadoTopHint: (n: number) => `${n} registros a su nombre`,
  kpiSinDato: "Sin datos",
  kpiVsAnterior: "vs. periodo anterior",
  kpiVariacionAria: (v: number) => `Variación ${v > 0 ? "al alza" : v < 0 ? "a la baja" : "sin cambio"} respecto al periodo anterior`,
  rankingPuesto: (n: number) => `Puesto ${n}`,
  analiticaSinDatos: "Sin datos para los filtros actuales.",
  analiticaVaciaCta: "Registrar incidencia",
  analiticaVaciaTitulo: "No hay incidencias en este conjunto",
  errorEstadisticas: "No se pudieron cargar las estadísticas de incidencias.",
  errorEstadisticasAccion: "Puedes reintentar la carga con los mismos filtros.",
  reintentarCarga: "Reintentar",

  filtroArea: "Área",
  filtroEmpleado: "Empleado",
  placeholderBuscarEmpleado: "Buscar por nombre o número de empleado",
  tablaVaciaSugerenciaEmpleado:
    "Prueba con otro nombre, identificador o folio.",
  filtroSupervisor: "Supervisor",
  filtroTipo: "Tipo",
  filtroNoEmpleado: "No empleado",
  filtroFechaDesde: "Fecha desde",
  filtroFechaHasta: "Fecha hasta",
  filtroSubarea: "Subárea",
  optTodasSubareas: "Todas las subáreas",
  filtroEstado: "Estado",
  optEstatusAbierto: "Abierta",
  optEstatusInvestigacion: "En investigación",
  filtroPeriodo: "Periodo",

  optTodasAreas: "Todas las áreas",
  optCualquierSupervisor: "Cualquiera",
  optTodosTipos: "Todos los tipos",
  optCualquierEstado: "Cualquier estado",
  optUltimos30: "Últimos 30 días",
  optUltimos90: "Últimos 90 días",
  optAnio: "Último año",
  optTodoPeriodo: "Todo el periodo",

  limpiarFiltros: "Limpiar filtros",
  aplicarFiltros: "Aplicar filtros",
  filtrosAplicadosHint: "Ajusta los campos y pulsa «Aplicar filtros» para consultar el servidor.",

  tablaAria: "Listado de incidencias",
  filtrosTitulo: "Filtros de búsqueda",
  filtrosSeccionAria: "Filtros de búsqueda",
  colId: "ID",
  colEmpleadoId: "Empleado ID",
  colNoEmpleado: "No empleado",
  colAcciones: "Acciones",
  accionVer: "Ver",
  colNombre: "Nombre",
  colCategoria: "Categoría",
  colDetalle: "Detalle",
  colDescuentoPct: "Descuento %",
  colEstatusId: "Estatus ID",
  colSubarea: "Subárea",
  colCreacion: "Fecha de creación",
  colActualizacion: "Fecha de actualización",
  colEmpleado: "Empleado",
  colNumero: "Número",
  colArea: "Área",
  colTipo: "Tipo",
  colTipoIncidencia: "Tipo incidencia",
  colFecha: "Fecha",
  colEstado: "Estado",
  colPrioridad: "Prioridad",

  cargandoTabla: "Cargando incidencias…",
  tablaVacia: "No hay incidencias con los filtros actuales.",
  tablaVaciaTitulo: "No se encontraron incidencias",
  tablaVaciaDescripcion:
    "Intenta ajustar los filtros o registra una nueva incidencia laboral.",
  errorTabla: "Error al cargar la tabla.",
  sinDatosTrasError: "Sin datos disponibles.",
  registrosPorPagina: "Registros por página",

  mostrando: (desde: number, hasta: number, total: number) =>
    `Mostrando ${desde} a ${hasta} de ${total} incidencias`,
  mostrandoCero: "Mostrando 0 de 0 incidencias",

  anterior: "Anterior",
  siguiente: "Siguiente",

  toastExportMock: "Exportación de incidencias (mock) iniciada.",
  toastNuevaMock: "Flujo de nueva incidencia (mock).",
  toastFiltrosAvMock: "Filtros avanzados (próximamente).",

  accesoDenegadoTitulo: "Acceso restringido",
  accesoDenegadoTexto:
    "La vista de incidencias laborales está disponible solo para usuarios con rol Recursos Humanos, director, gerente o supervisor.",
  volverDashboard: "Volver al dashboard",

  sinNombre: "Sin nombre",
  etiquetaNoEmpleadoCorto: "No.",

  cardReportante: "Información del empleado reportante",
  cardDetalle: "Detalle de la incidencia",
  cardEvidencia: (n: number) => `Evidencia (${n})`,
  cardPersonal: "Personal involucrado",
  cardDescCompleta: "Descripción completa",
  cardLblNombre: "Nombre completo",
  cardLblNoEmpleado: "Número empleado",
  cardLblArea: "Área",
  cardLblSubarea: "Subárea",
  cardLblPuesto: "Puesto",
  cardLblSupervisor: "Supervisor directo",
  cardLblTipo: "Tipo",
  cardLblSubtipo: "Subtipo",
  cardLblFechaHora: "Fecha y hora",
  cardLblSemana: "Semana",
  cardLblDescuentoPorcentaje: "Descuento porcentaje",
  cardLblUbicacion: "Ubicación",
  cardEstado: "Estado",
  cardIdReporte: "ID de reporte",
  cardPrioridad: "Prioridad",
  cardSlaTiempo: "Tiempo transcurrido",
  cardSlaObjetivo: (h: number) => `(SLA: ${h}H)`,
  cardSlaDentro: "Dentro de tiempo",
  cardSlaFuera: "Fuera de tiempo",
  cardSlaProgreso: "Progreso SLA",
  cardVerHistorial: "Ver historial de registro",
  cardSinEvidencias: "Sin evidencias adjuntas.",
  cardSinPersonal: "Sin personal adicional registrado.",
  cardDescargaAria: "Descargar archivo",
  badgeRolTestigo: "Testigo",
  badgeRolAfectado: "Afectado",
  badgeRolInvolucrado: "Involucrado",
  toastHistorialMock: "Historial de registro (próximamente).",
  toastDescargaMock: "Descarga de evidencia (simulación).",

  detalleModalTitulo: "Detalle de incidencia",
  detalleModalCerrar: "Cerrar detalle",

  estadoCerrada: "Cerrada",
  cardSlaHistoricoTitulo: "SLA (histórico)",
  cardSlaHistoricoDescripcion:
    "Caso cerrado. El seguimiento de tiempo de respuesta quedó registrado para auditoría.",
  cardSlaHistoricoFinalizado: "SLA finalizado",
  cardSlaTiempoTotal: "Tiempo total registrado",
} as const;
