/**
 * Textos de UI — vista administrativa de incidencias laborales (rol RH).
 */

export const INC_COPY = {
  tituloPagina: "Incidencias",
  subtitulo:
    "Registro y seguimiento de incidencias disciplinarias y operativas.",
  listadoTitulo: "Listado de incidencias",
  listadoSubtitulo: (total: number) =>
    total === 1 ? "1 incidencia encontrada" : `${total} incidencias encontradas`,
  exportar: "Exportar incidencias",
  nueva: "Nueva incidencia",
  filtrosAvanzadosAria: "Filtros avanzados",

  kpiAbiertas: "Incidencias abiertas",
  kpiAbiertasMicro: "Requieren atención",
  kpiInvestigacion: "En investigación",
  kpiInvestigacionMicro: "Pendientes de seguimiento",
  kpiResueltas: "Resueltas",
  kpiResueltasMicro: "Completadas o cerradas",
  kpiCriticas: "Críticas",
  kpiCriticasMicro: "Prioridad máxima",

  errorMetricas: "No se pudieron calcular las métricas.",

  filtroArea: "Área",
  filtroEmpleado: "Empleado",
  placeholderBuscarEmpleado: "Buscar por nombre o número de empleado",
  tablaVaciaSugerenciaEmpleado:
    "Prueba con otro nombre, identificador o folio.",
  filtroSupervisor: "Supervisor",
  filtroTipo: "Tipo",
  filtroNoEmpleado: "No empleado",
  filtroEstado: "Estado",
  filtroPeriodo: "Periodo",

  optTodasAreas: "Todas las áreas",
  optCualquierSupervisor: "Cualquiera",
  optTodosTipos: "Todos los tipos",
  optCualquierEstado: "Cualquier estado",
  optUltimos30: "Últimos 30 días",
  optUltimos90: "Últimos 90 días",
  optAnio: "Último año",
  optTodoPeriodo: "Todo el periodo",

  limpiarFiltros: "Limpiar filtros",
  aplicarFiltros: "Aplicar filtros",
  filtrosAplicadosHint: "Ajusta los campos y pulsa «Aplicar filtros» para consultar el servidor.",

  tablaAria: "Listado de incidencias",
  filtrosTitulo: "Filtros de búsqueda",
  filtrosSeccionAria: "Filtros de búsqueda",
  colId: "ID",
  colEmpleadoId: "Empleado ID",
  colNoEmpleado: "No empleado",
  colAcciones: "Acciones",
  accionVer: "Ver",
  colNombre: "Nombre",
  colCategoria: "Categoría",
  colDetalle: "Detalle",
  colDescuentoPct: "Descuento %",
  colEstatusId: "Estatus ID",
  colSubarea: "Subárea",
  colCreacion: "Fecha de creación",
  colActualizacion: "Fecha de actualización",
  colEmpleado: "Empleado",
  colNumero: "Número",
  colArea: "Área",
  colTipo: "Tipo",
  colFecha: "Fecha",
  colEstado: "Estado",
  colPrioridad: "Prioridad",

  cargandoTabla: "Cargando incidencias…",
  tablaVacia: "No hay incidencias con los filtros actuales.",
  tablaVaciaTitulo: "No se encontraron incidencias",
  tablaVaciaDescripcion:
    "Intenta ajustar los filtros o registra una nueva incidencia laboral.",
  errorTabla: "Error al cargar la tabla.",
  sinDatosTrasError: "Sin datos disponibles.",
  registrosPorPagina: "Registros por página",

  mostrando: (desde: number, hasta: number, total: number) =>
    `Mostrando ${desde} a ${hasta} de ${total} incidencias`,
  mostrandoCero: "Mostrando 0 de 0 incidencias",

  anterior: "Anterior",
  siguiente: "Siguiente",

  toastExportMock: "Exportación de incidencias (mock) iniciada.",
  toastNuevaMock: "Flujo de nueva incidencia (mock).",
  toastFiltrosAvMock: "Filtros avanzados (próximamente).",

  accesoDenegadoTitulo: "Acceso restringido",
  accesoDenegadoTexto:
    "La vista de incidencias laborales está disponible solo para usuarios con rol Recursos Humanos, director, gerente o supervisor.",
  volverDashboard: "Volver al dashboard",

  sinNombre: "Sin nombre",

  cardReportante: "Información del empleado reportante",
  cardDetalle: "Detalle de la incidencia",
  cardEvidencia: (n: number) => `Evidencia (${n})`,
  cardPersonal: "Personal involucrado",
  cardDescCompleta: "Descripción completa",
  cardLblNombre: "Nombre completo",
  cardLblNoEmpleado: "Número empleado",
  cardLblArea: "Área",
  cardLblSubarea: "Subárea",
  cardLblPuesto: "Puesto",
  cardLblSupervisor: "Supervisor directo",
  cardLblTipo: "Tipo",
  cardLblFechaHora: "Fecha y hora",
  cardLblSemana: "Semana",
  cardLblDescuentoPorcentaje: "Descuento porcentaje",
  cardLblUbicacion: "Ubicación",
  cardEstado: "Estado",
  cardIdReporte: "ID de reporte",
  cardPrioridad: "Prioridad",
  cardSlaTiempo: "Tiempo transcurrido",
  cardSlaObjetivo: (h: number) => `(SLA: ${h}H)`,
  cardSlaDentro: "Dentro de tiempo",
  cardSlaFuera: "Fuera de tiempo",
  cardSlaProgreso: "Progreso SLA",
  cardVerHistorial: "Ver historial de registro",
  cardSinEvidencias: "Sin evidencias adjuntas.",
  cardSinPersonal: "Sin personal adicional registrado.",
  cardDescargaAria: "Descargar archivo",
  badgeRolTestigo: "Testigo",
  badgeRolAfectado: "Afectado",
  badgeRolInvolucrado: "Involucrado",
  toastHistorialMock: "Historial de registro (próximamente).",
  toastDescargaMock: "Descarga de evidencia (simulación).",

  detalleModalTitulo: "Detalle de incidencia",
  detalleModalCerrar: "Cerrar detalle",

  estadoCerrada: "Cerrada",
  cardSlaHistoricoTitulo: "SLA (histórico)",
  cardSlaHistoricoDescripcion:
    "Caso cerrado. El seguimiento de tiempo de respuesta quedó registrado para auditoría.",
  cardSlaHistoricoFinalizado: "SLA finalizado",
  cardSlaTiempoTotal: "Tiempo total registrado",
} as const;
